env:
  CIRRUS_CLONE_DEPTH: 1

only_if: $CIRRUS_PR == ''


##======= FreeBSD =========
## https://cirrus-ci.org/guide/FreeBSD/
#freebsd_task:
#  name: FreeBSD
#  compute_engine_instance:
#    image_project: freebsd-org-cloud-dev
#    image: family/freebsd-13-1
#    image: family/freebsd-12-4
#    image: family/freebsd-11-4
#    platform: freebsd
#    cpu: 1
#    memory: 1GB
##  pkginstall_script:
##    - pkg install -y ...
#  build_script:
#    - ./scripts/test_ci.sh


#======= OpenBSD =========
#openbsd_task:
#  name: OpenBSD
#  compute_engine_instance:
#    image_project: pg-ci-images
#    image: family/pg-ci-openbsd-vanilla-7-2
#    platform: openbsd
#    cpu: 1
#    memory: 1GB
##  install_script:
##    - pkg_add ...
#  script:
#    - ./scripts/test_ci.sh


##======= NetBSD =========
#netbsd_task:
#  name: NetBSD
#  compute_engine_instance:
#    image_project: pg-ci-images
#    image: family/pg-ci-netbsd-vanilla-9-2
#    platform: netbsd
#    cpu: 1
#    memory: 1GB
##  install_script:
##    - export XVARX=xxx
##    - pkg_add ...
#  script:
#    - ./scripts/test_ci.sh


#======= macOS =========
## https://github.com/cirruslabs/macos-image-templates
#macos_task:
#  name: macOS Ventura
#  macos_instance:
#    image: ghcr.io/cirruslabs/macos-ventura-base:latest
#    cpu: 1
#    memory: 1GB
##  pkginstall_script:
##    - brew install ...
#  build_script:
#    - ./scripts/test_ci.sh


#======= Alpine Linux =========
#alpine_linux_task:
#  name: Alpine Linux
#  container:
#    image: alpine
##   image: alpine:3.17
#    cpu: 1
#    memory: 1GB
#  pkginstall_script:
#    - apk add --no-cache build-base
#  build_script:
#    - ./scripts/test_ci.sh


task:
  name: Test in docker img(s)
  compute_engine_instance:
#    image_project: cos-cloud
#    image_family: cos-stable
    image_project: fedora-coreos-cloud
    image_family: fedora-coreos-stable
    platform: linux
    cpu: 1
    memory: 2G
#  only_if: $CIRRUS_PR == ''
  # temp hack, test_ci.sh needs a special logic for cirrus
  env:
    CIRCLECI: true
  build_script:
    - ./scripts/test_ci.sh

